stages:
  - push_to_github

push_to_github_job:
  stage: push_to_github
  only:
    - master
  script:
    - git remote add github https://NizomDjuraev:${GITHUB_TOKEN}@github.com/NizomDjuraev/CardScanAndGrade.git
    - git push github HEAD:master
