name: Mirror to GitLab
on: [push]
jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the GitHub repository to GitLab
      env:
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      run: |
        git clone https://github.com/${{ github.repository }} tmp_repo
        cd tmp_repo
        git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.cci.drexel.edu/nd5961/senior-design-project.git
        git push --mirror gitlab
